# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_cliente_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default=2, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
